require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe XmlFileDownloadsController do

  # This should return the minimal set of attributes required to create a valid
  # XmlFileDownload. As you add validations to XmlFileDownload, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all xml_file_downloads as @xml_file_downloads" do
      xml_file_download = XmlFileDownload.create! valid_attributes
      get :index
      assigns(:xml_file_downloads).should eq([xml_file_download])
    end
  end

  describe "GET show" do
    it "assigns the requested xml_file_download as @xml_file_download" do
      xml_file_download = XmlFileDownload.create! valid_attributes
      get :show, :id => xml_file_download.id.to_s
      assigns(:xml_file_download).should eq(xml_file_download)
    end
  end

  describe "GET new" do
    it "assigns a new xml_file_download as @xml_file_download" do
      get :new
      assigns(:xml_file_download).should be_a_new(XmlFileDownload)
    end
  end

  describe "GET edit" do
    it "assigns the requested xml_file_download as @xml_file_download" do
      xml_file_download = XmlFileDownload.create! valid_attributes
      get :edit, :id => xml_file_download.id.to_s
      assigns(:xml_file_download).should eq(xml_file_download)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new XmlFileDownload" do
        expect {
          post :create, :xml_file_download => valid_attributes
        }.to change(XmlFileDownload, :count).by(1)
      end

      it "assigns a newly created xml_file_download as @xml_file_download" do
        post :create, :xml_file_download => valid_attributes
        assigns(:xml_file_download).should be_a(XmlFileDownload)
        assigns(:xml_file_download).should be_persisted
      end

      it "redirects to the created xml_file_download" do
        post :create, :xml_file_download => valid_attributes
        response.should redirect_to(XmlFileDownload.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved xml_file_download as @xml_file_download" do
        # Trigger the behavior that occurs when invalid params are submitted
        XmlFileDownload.any_instance.stub(:save).and_return(false)
        post :create, :xml_file_download => {}
        assigns(:xml_file_download).should be_a_new(XmlFileDownload)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        XmlFileDownload.any_instance.stub(:save).and_return(false)
        post :create, :xml_file_download => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested xml_file_download" do
        xml_file_download = XmlFileDownload.create! valid_attributes
        # Assuming there are no other xml_file_downloads in the database, this
        # specifies that the XmlFileDownload created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        XmlFileDownload.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => xml_file_download.id, :xml_file_download => {'these' => 'params'}
      end

      it "assigns the requested xml_file_download as @xml_file_download" do
        xml_file_download = XmlFileDownload.create! valid_attributes
        put :update, :id => xml_file_download.id, :xml_file_download => valid_attributes
        assigns(:xml_file_download).should eq(xml_file_download)
      end

      it "redirects to the xml_file_download" do
        xml_file_download = XmlFileDownload.create! valid_attributes
        put :update, :id => xml_file_download.id, :xml_file_download => valid_attributes
        response.should redirect_to(xml_file_download)
      end
    end

    describe "with invalid params" do
      it "assigns the xml_file_download as @xml_file_download" do
        xml_file_download = XmlFileDownload.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        XmlFileDownload.any_instance.stub(:save).and_return(false)
        put :update, :id => xml_file_download.id.to_s, :xml_file_download => {}
        assigns(:xml_file_download).should eq(xml_file_download)
      end

      it "re-renders the 'edit' template" do
        xml_file_download = XmlFileDownload.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        XmlFileDownload.any_instance.stub(:save).and_return(false)
        put :update, :id => xml_file_download.id.to_s, :xml_file_download => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested xml_file_download" do
      xml_file_download = XmlFileDownload.create! valid_attributes
      expect {
        delete :destroy, :id => xml_file_download.id.to_s
      }.to change(XmlFileDownload, :count).by(-1)
    end

    it "redirects to the xml_file_downloads list" do
      xml_file_download = XmlFileDownload.create! valid_attributes
      delete :destroy, :id => xml_file_download.id.to_s
      response.should redirect_to(xml_file_downloads_url)
    end
  end

end
