require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe XmlFileDownloadsController do

  # This should return the minimal set of attributes required to create a valid
  # XmlFileDownload. As you add validations to XmlFileDownload, be sure to
  # update the return value of this method accordingly.
  before :each do
    Shop.create({:name => "alza.sk", :url => "Http://www.alza.sk"})
  end

  def valid_attributes
    {:shop_id => 1}
  end

  describe "GET index" do
    it "assigns all xml_file_downloads as @xml_file_downloads" do
      xml_file_download = XmlFileDownload.create! valid_attributes
      get :index
      assigns(:xml_file_downloads).should eq([xml_file_download])
    end
  end

  describe "GET show" do
    it "assigns the requested xml_file_download as @xml_file_download" do
      xml_file_download = XmlFileDownload.create! valid_attributes
      get :show, :id => xml_file_download.id.to_s
      assigns(:xml_file_download).should eq(xml_file_download)
    end
  end

  describe "GET new" do
    it "assigns a new xml_file_download as @xml_file_download" do
      get :new
      assigns(:xml_file_download).should be_a_new(XmlFileDownload)
    end
  end

  describe "POST create" do

    describe "with invalid params" do
      it "assigns a newly created but unsaved xml_file_download as @xml_file_download" do
        # Trigger the behavior that occurs when invalid params are submitted
        XmlFileDownload.any_instance.stub(:save).and_return(false)
        post :create, :xml_file_download => {}
        assigns(:xml_file_download).should be_a_new(XmlFileDownload)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        XmlFileDownload.any_instance.stub(:save).and_return(false)
        post :create, :xml_file_download => {}
        response.should render_template("new")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested xml_file_download" do
      xml_file_download = XmlFileDownload.create! valid_attributes
      expect {
        delete :destroy, :id => xml_file_download.id.to_s
      }.to change(XmlFileDownload, :count).by(-1)
    end
  end

end
